### ISSUE TITLE
Open /all endpoint

### ISSUE THREAD

**Issue by scoiatael** [jsonresume/registry-functions#1]
Hey, I'd simply like to let you know that having [open endpoint that lists all past users](http://registry.jsonresume.org/all) might not be the best choice here :)

If you'd like to expose some metrics, maybe simply using counter would be enough?

**Comment by thomasdavis** [comment]
lol decently late reply, just now thinking of a `/stats` endpoint. 

Something like 

```js
{
  total: 3600,
  themes: { 
    elegant: 540,
    thin: 210, 
     ... 
   }
}
```

`themes` being the count of how many people use that theme on the hosted registry.

Other contenders could be the amount of page views total, and the total on average.

Keeping this issue open for suggestions for other useful stats.
