### ISSUE TITLE
Feature: support repositories and not only gists

### ISSUE THREAD

**Issue by felipecrs** [jsonresume/registry-functions#17]
I would like to be able to use a full repository to host my resume, so I could pin in my profile as usual.

Template:

`https://github.com/${username}/resume/resume.json`

or, even more directly:

`https://github.com/${username}/resume/raw/master/resume.json`

In order to not break anything, I suggest to implement a redundancy:

Check if a Gist is found, if yes use it, otherwise fallback to the repository.

**Comment by thomasdavis** [comment]
Just had a look at how hard it might be to implement. 

Seems quite easy, I will have a play around at some point.

**Comment by cybairfly** [comment]
My first thought when deploying this. Would be very welcome.

**Comment by thomasdavis** [comment]
@felipecrs @cybairfly I've got this feature working at https://registry.jsonresume.org/repo/thomasdavis as a prototype.

I kinda agree in retrospect it would actually be a better solution. It would promote people to add extra tooling around their resumes. 

The only problem is that Github aggressively caches the url end point https://raw.githubusercontent.com/thomasdavis/resume/master/resume.json that can't be cache busted with query strings.

It's on a 5 minute timer, which kinda sucks... gist I can cache bust in seconds so it feels like you work on it in real time. 

Any ideas?

p.s. only took me two years of covid to do this ahaha

**Comment by felipecrs** [comment]
Does https://github.com/thomasdavis/resume/raw/master/resume.json help?

**Comment by thomasdavis** [comment]
It just redirects to https://raw.githubusercontent.com/thomasdavis/resume/master/resume.json so it's what get's loaded.

**Comment by felipecrs** [comment]
Got it. The only way I can find is something like this:

```console
$ revision=$(git ls-remote https://github.com/thomasdavis/resume HEAD | awk '{ print $1 }')

$ curl -fsSL https://raw.githubusercontent.com/thomasdavis/resume/${revision}/resume.json
```

**Comment by thomasdavis** [comment]
Yeah great job, makes sense, will try it. (Will obviously be slower but the gist approach is slow too anyway)

**Comment by thomasdavis** [comment]
Can write some instructions for a Github action that makes it instant or something. (Currently copying your README approach, could build something similar)

**Comment by cybairfly** [comment]
Great to hear that it will be possible. No idea how to achieve that but I guess Felipe's idea will work.

**Comment by jona-sassenhagen** [comment]
This would be a nice feature.

**Comment by thomasdavis** [comment]
@felipecrs @cybairfly @jona-sassenhagen 

Don't know why it has taken me this long to think of an easy way but here it is -> https://github.com/thomasdavis/resume 

Just use a Github Action to publish a gist when you ever want (in my case, every push)

**Comment by felipecrs** [comment]
That works, thanks for providing the example. However it didn't have to be necessary. :)

I'll understand if you prefer to close this issue with this solution, though.

**Comment by thomasdavis** [comment]
No worries. I've actually wanted this myself since the project was first created aha
