### ISSUE TITLE
Translations for resume ?

### ISSUE THREAD

**Issue by erwanlbp** [jsonresume/registry-functions#18]
Hi,
Not sure if it's the right place to ask, but is there a plan to add the possibility to translate themes ? Maybe with some `&lang=fr` and adding translations in themes ...

**Comment by wuiler** [comment]
Same opinion. I DONT KNOW about node.js or express but maybe passing &lang=es or &lang=fr we coud change and add a gist 
like fr.resume.json without adding any i18n package to complicate things.  
Then we could verify if file exists too on Gists and added to firestore.  


```
app.get("/:username", async (req, res) => {
    const username = req.params.username;


    let defaultResume = "resume.json";
    let resumeName = defaultResume;
    
    let lang = req.query.lang;
    if (!lang) {
        resumeName = lang + defaultResume;
    } 
 ...
 ...
 ...
    const resumeUrl = _.find(gistData.data, f => {
          return f.files[resumeName];
        });
```

**Comment by thomasdavis** [comment]
Closing this in favor of https://github.com/jsonresume/jsonresume.org/issues/288
