### ISSUE TITLE
Automatic deploys aren't working.

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/registry-functions#28]
If you manually deploy with Firebase it can handle the repo size but something to do with the PR deploy doesn't seem to work.

**Comment by thomasdavis** [comment]
Worst case, themes will have to be deployed separately and a router placed in front.

**Comment by thomasdavis** [comment]
They are working, need to update README to make sure PR's include an `npm i` to also update the package-lock of the `./function` folder

**Comment by cybairfly** [comment]
Is this related to the registry being down now for a couple days with "This is not a valid Github username"?

**Comment by thomasdavis** [comment]
Fixed now.
