### ISSUE TITLE
feature: Install themes on demand

### ISSUE THREAD

**Issue by pke** [jsonresume/registry-functions#4]
It does not look like the current code can dynamically load themes. Maybe it only wants to load a curated list of themes for security reasons?

How about using https://github.com/Manak/npm-programmatic#readme to dynamically load themes instead, if this does not create security issues. But given the relaxed package.json definition for the already included themes this does not seem to be of concern?

What then if any the themes could be more limited and basically just provide the templates for html and css? Are there any themes out there that need some heavy programming?
Even if so, they could run kind of sandboxed by calling their source code inside a `new Function` declaration and only giving them access to handlebars, liquid or such frameworks.

**Comment by thomasdavis** [comment]
Thanks @pke for the suggestion and sorry for the delay. 

The old server use to run any and all themes, installing them as they were required. 

But it was insecure and we have also since moved to firebase functions for hosting. 

I will check out pke and see if it could be used.

**Comment by thomasdavis** [comment]
Labelled as high priority, it's annoying that you can't have dynamic themes, and there must be a way around it...
