### ISSUE TITLE
Github Workflow Failure

### ISSUE THREAD

**Issue by agithony** [jsonresume/registry-functions#44]
I tried fixing (to no avail) the GitHub workflow for this project. The error is:
`Error: Error parsing triggers: Cannot find module '../creds.json'`

Looking into the code, you can see it is going into the else block which isn't what we want.
`if (process.env.NODE_ENV === "production")`

How do we fix this?
I imported the npm package `dotenv` and created a .env file with the variable `NODE_ENV=production`. Still no luck. The code still doesn't go into that condition. If it does, I think the workflow will pass.

Any help or suggestions would be appreciated!

**Comment by thomasdavis** [comment]
@anthonyjdella thanks for looking into it! 

I'm more curious to know why you are interested in the deployment of this repo. 

If you are keen on setting up an alternative host let me know and we can sort it out.

**Comment by agithony** [comment]
@thomasdavis I was interested in this repo because I made updates to the JSON schema and wanted to be able to go to https://registry.jsonresume.org/ and see that schema in place. I wasn't able to do it, so I kind of reverse-engineered it and now have my own firebase function for it lol

**Comment by thomasdavis** [comment]
Thanks @anthonyjdella, going to close this issue.

Would love to see your work if your repo is public.
