### ISSUE TITLE
url is case sensitive on the github username

### ISSUE THREAD

**Issue by tattwamasi** [jsonresume/registry-functions#69]
First off, thanks for the project and all this work.  Just wanted to note something that threw me for a while after setting up my new gist version of things. I searched the issues but didn't see it noted, so just wanted to get it written down.

My username is apparently Tattwamasi with the initial cap, and getting the casing right is required in the registry server URL.  This was unexpected.  You can't necessarily even see the casing on your username depending on where you see it in Github.  I would not expect any of the URL itself to be case sensitive.

**Comment by thomasdavis** [comment]
@tattwamasi Thanks for the feedback. If I access https://registry.jsonresume.org/THOMASdavis 

it seems to work.
