### ISSUE TITLE
Request a theme

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/registry-functions#7]
If you want to add an official theme please make a pull request where you add it to `./functions/package.json` once accepted, the branch will automatically be deployed to firebase using Github actions.

**Comment by thomasdavis** [comment]
Also try to include a screenshot or live demo in the PR.

**Comment by sundowndev** [comment]
I get redirected to this issue even for using official themes `resume serve --port 8080 --theme paper`

**Comment by Poslovitch** [comment]
Same here, with `resume serve --theme onepage`

**Comment by lfarci** [comment]
I just got redirected here too after executing `resume serve --theme paper resume.json`.

Edit: my bad, after installing the [`jsonresume-theme-paper`](https://www.npmjs.com/package/jsonresume-theme-paper) npm package globally, I was able to successfully use the official theme.

**Comment by thomasdavis** [comment]
Hrmmmm can you paste full output

Try to install theme globally on your comp 

Npm I -g jsonresume-theme-paper

**Comment by mubarakshow** [comment]
**Solved**
if you tried to install in a project rather than globally, you can do the following to run.

1) go into the node_modules folder
`cd node_module`
2) go into the installed theme folder
`cd jsonresume-theme-{theme name}`
3) add your `resume.json` file to the root of the theme
4) run this command: `resume serve`

**Comment by TARIQvs** [comment]
Even the above solution didn't work for me. But global installation is a help.

**Comment by thomasdavis** [comment]
Going to take a look tonight to see if there is any better solutions or at least add some helper text.

**Comment by cphoover** [comment]
I thought it was supposed to find custom themes you are developing local to the root of the project (outside of node_modules)

**Comment by jackkeller** [comment]
How are updates to themes handled? If I submit a PR for one but then update it at a later date is that a new PR with a version bump?

**Comment by thomasdavis** [comment]
@jackkeller yes, the new PR just requires to change the version.
