### ISSUE TITLE
Rendering broken for several themes

### ISSUE THREAD

**Issue by alexanderdavide** [jsonresume/registry-functions#70]
The hosting has a problem that some themes aren't delivered properly. These include [theme](https://registry.jsonresume.org/thomasdavis?theme=paper), [stackoverflow](https://registry.jsonresume.org/thomasdavis?theme=stackoverflow) and [spartan](https://registry.jsonresume.org/thomasdavis?theme=spartan). The list probably goes on and the problem seems to be the same for all incidences.

**Comment by agithony** [comment]
Same issue here. Looks like there was a [breaking change](https://github.com/jsonresume/registry-functions/commit/b275c45dcd63f590d1a5c19083c6341e23eb6ae1) added 2 weeks ago

**Comment by thomasdavis** [comment]
Ahhhh thanks guys, fixing now

**Comment by thomasdavis** [comment]
Working again, I'm using `pm2` to run it on a server, it auto restarts when failures but keeps resetting the node version. Gotta figure it out...

**Comment by thomasdavis** [comment]
Kinda weird how those themes crash on node 18 too

**Comment by thomasdavis** [comment]
I will move the hosting back to firebase functions this weekend (a lot more reliable than my linux box)

**Comment by alexanderdavide** [comment]
@thomasdavis, have you already moved hosting back to Firebase? If yes, the problem still exists or is appearing again.

**Comment by thomasdavis** [comment]
The hosting is now on Vercel, and templates that use `fs` to render will fail. Working on fixing those templats.
