### ISSUE TITLE
Output not updating when gist is changed

### ISSUE THREAD

**Issue by shravan2709** [jsonresume/registry-functions#71]
Any changes to my gist are not being reflected in the rendered resume at https://registry.jsonresume.org/shravan2709. The page still shows an old error 

> Resume json invalid - [{"code":"PATTERN","params":["^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$","May 2014"],"message":"String does not match pattern ^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$: May 2014","path":"#/education/1/endDate","description":"e.g. 2014-06-29"}] - Please visit https://github.com/jsonresume/registry-functions/issues/27

but I deleted the education section entirely to test it. I also just deleted the gist itself, and I still see the same page. Is this being cached server-side, and if yes, is there a way I can cache bust? 

Not being able to see changes in real-time makes it pretty hard to work with - especially because the rendering works great using the command line tool but there seems to be extra JSON validation in the registry.

**Comment by thomasdavis** [comment]
Is this error still happening? 

It does have a cache buffer of 80 seconds. 

It's probably related to this error  https://github.com/jsonresume/registry-functions/issues/70

**Comment by QuentinSP** [comment]
Hello, I also have this error. How can I solve it ?

**Comment by thomasdavis** [comment]
@QuentinSP Have you made sure that your gist is public?

**Comment by thomasdavis** [comment]
I figured this out for anyone who was having this issue. 

The cache control was not setting correctly when the resume wasn't actually rendered.
